-- Talents:
-- Warrior:
WARRIOR_DEEP_PROT = "WARRIOR_DEEP_PROT"
WARRIOR_FURY = "WARRIOR_FURY"
WARRIOR_FURY_PROT = "WARRIOR_FURY_PROT"

-- Warlock:
WARLOCK_DS_RUIN = "WARLOCK_DS_RUIN"
WARLOCK_SM_RUIN = "WARLOCK_SM_RUIN"

-- Rogue:
ROGUE_DAGGER = "ROGUE_DAGGER"
ROGUE_SWORD = "ROGUE_SWORD"

-- Paladin:
PALADIN_HOLY = "PALADIN_HOLY"

-- Priest
PRIEST_HOLY = "PRIEST_HOLY"
PRIEST_SHADOW = "PRIEST_SHADOW"
PRIEST_POWER_INFUSION = "PRIEST_POWER_INFUSION"

-- mage:
MAGE_DEEP_FROST = "MAGE_DEEP_FROST"
MAGE_ARCANE_FROST = "MAGE_ARCANE_FROST"
MAGE_FIRE = "MAGE_FIRE"

-- Hunter:
HUNTER_MARKSMAN = "HUNTER_MARKSMAN"

-- Druid:
DRUID_TANK = "DRUID_TANK"
DRUID_BALANCE = "DRUID_BALANCE"
DRUID_RESTO = "DRUID_RESTO"
