AQ40 = "Temple of Ahn'Qiraj"
AQ20 = "Ruins of Ahn'Qiraj"
BWL = "Blackwing Lair"
MC = "Molten Core"
ZG = "Zul'Gurub"

-- ZG subzones:
ZG_JEKLIK = "Altar of Hir'eek"
ZG_VENOXIS = "Coil"
ZG_MARLI = "Shadra'zaar"
ZG_MANDOKIR = "Hakkari Grounds"
ZG_THEKAL = "Naze of Shirvallah"
ZG_SUMMON = "Edge of Madness"
ZG_ARLOKK = "Temple of Bethekk"
ZG_GHAZ_RANKA = "Pagle's Pointe"
ZG_JINDO = "Bloodfire Pit"
ZG_HAKKAR = "Altar of the Blood God"
